name: shelf_session
description: The `shelf_session` is the implementation of `cookiesMiddleware` and  `sessionMiddleware` for `shelf`.
repository:  https://github.com/mezoni/shelf_session
version: 0.1.2
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  shelf: ^1.4.0
dev_dependencies:
  lints: ^2.0.0
  shelf_router: ^1.1.3
  shelf_static: ^1.1.1
